on: [push]

jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v2.1.3 # Get Latest Version from https://github.com/marketplace/actions/soos-core-sca
      with:
        project_name: "GitHub Actions - SCA from branch with v2.1.3"  
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: 'https://qa-api.soos.io/api/'
        log_level: "DEBUG"
        package_managers: "Go,Homebrew,Java,NPM,NuGet,Python"
        on_failure: "continue_on_failure"
        directories_to_exclude: '**/go files/**'
        files_to_exclude: '**/package.json'
        branch_name: "test-branch"
        #output_format: SARIF
        #verbose: true
        #build_version: 2.0.0
