on: [push]

jobs:
  synchronous-analysis-with-blocking-result:
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status    
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@735f232aff5e11487d6f76d2f863ab2954fda777 #Get Latest Version from https://github.com/marketplace/actions/soos-core-sca
      with:
        project_name: "GitHub Actions - SCA"  
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: 'https://qa-api.soos.io/api/'
        log_level: DEBUG
        package_managers: "cFamily"  
        sca_version: 4.0.12-pre.1
        export_format: soosissues
        export_file_type: html
        
      # Cargar el directorio generado como artefacto
    - uses: actions/upload-artifact@v4
      with:
        name: sast-analysis-output
        path: |
              ${{ github.workspace }}/*.cyclonedx.json
              ${{ github.workspace }}/*.cyclonedx.xml
              ${{ github.workspace }}/*.spdx.json
              ${{ github.workspace }}/*.spdx.txt
              ${{ github.workspace }}/*.sarif.json
              ${{ github.workspace }}/*.csafvex.json
              ${{ github.workspace }}/*.sooslicenses.hmtl
              ${{ github.workspace }}/*.sooslicenses.csv
              ${{ github.workspace }}/*.soospackages.hmtl
              ${{ github.workspace }}/*.soospackages.csv
              ${{ github.workspace }}/*.soosvulnerabilities.hmtl
              ${{ github.workspace }}/*.soosvulnerabilities.csv
              ${{ github.workspace }}/*.soosissues.hmtl
              ${{ github.workspace }}/*.soosissues.csv
              
