on: [push]

jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@feature/PA-10432 # Get Latest Version from https://github.com/marketplace/actions/soos-core-sca
      with:
        project_name: "GitHub Actions - SCA"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: 'https://qa-api.soos.io/api/'
